### ISSUE TITLE
Error running visual lizer_rllib.py

### ISSUE THREAD

**Issue by liuxgff** [eugenevinitsky/sequential_social_dilemma_games#156]
Hello, I am very interested in your article, but I encountered the following errors in code execution. I hope I can get your guidance.

Errors occurred:

OMP: Info#212: KMP_AFFINITY: decoding x 2 APIC ids.

OMP: Info#210: KMP_AFFINITY: Affinity capable, using global CPUID leaf 11 info

OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7

OMP: Info #156: KMP_AFFINITY: 8 available OS procs

OMP: Info #157: KMP_AFFINITY: Uniform topology

OMP: Info #179: KMP_AFFINITY: 1 packages x 4 cores/pkg x 2 threads/core (4 total cores)

OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:

OMP: Info_1: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0

OMP: Info_1: KMP_AFFINITY: OS proc 4 maps to package 0 core 0 thread 1

OMP: Info_1: KMP_AFFINITY: OS proc 1 maps to package 0 core 1 thread 0

OMP: Info_1: KMP_AFFINITY: OS proc 5 maps to package 0 core 1 thread 1

OMP: Info_1: KMP_AFFINITY: OS proc 2 maps to package 0 core 2 thread 0

OMP: Info_1: KMP_AFFINITY: OS proc 6 maps to package 0 core 2 thread 1

OMP: Info_1: KMP_AFFINITY: OS proc 3 maps to package 0 core 3 thread 0

OMP: Info_1: KMP_AFFINITY: OS proc 7 maps to package 0 core 3 thread 1

OMP: Info_: KMP_AFFINITY: PID 16827 TID 16827 thread 0 bound to OS proc set 0

Meanwhile ImportError: cannot import name'try_import_tf'from'ray.rllib.utils'

**Comment by eugenevinitsky** [comment]
Hi, sorry for the delay! I honestly have no idea what's happening here, I'd recommend reposting in the rllib github issues page.

**Comment by liuxgff** [comment]
Thank you very much for your reply.

Now I've got the environment, but to be honest, I'm a beginner. I really don't know how to run this code.
If so, I wonder if you can direct me to run the steps in detail, or what part of the code I need to add. Thank you so much.

This error occurred when I ran visual lizer_rllib.py
Usage: visual lizer_rllib.py [- h] [- run RUN] [- num-rollouts NUM_ROLLOUTS]
                                                         [--save-video] [--render]
                                                          result_dir checkpoint_num
Vislizer_rllib.py: error: the following arguments are required: result_dir, checkpoint_num

But I really don't know where to look for these parameter inputs.

**Comment by liuxgff** [comment]
Several errors occurred while running train_baseline, similar to:

Use FIFO scheduling algorithm.

Resources requested: 0.0/2 CPUs, 0/1 GPUs

Memory usage on this node: 6.0/8.2 GB

Result logdir: / home/liu/ray_results/cleanup_A3C

Number of trials: 1 ({'ERROR': 1})

ERROR trials:

- A3C_cleanup_env_0: ERROR, 4 failures: / home/liu/ray_results/cleanup_A3C/A3C_cleanup_env_0_2019-07-25_10-27-48 vqi4d9ky/error_2019-07-25_10-29-30.txt


Traceback (most recent call last):

File "train_baseline.py", line 180, in <module>

Tf. app. run (main)

File "/ home/liu/anaconda3/envs/causal_2/lib/python 3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run

_ sys. exit (main (argv))

File "train_baseline.py", line 174, in main

"Config": config,

File "/ home/liu/anaconda3/envs/causal_2/lib/python 3.6/site-packages/ray/tune/tune.py", line 189, in run_experiments

Raise TuneError ("Trials did not complete", errored_trials)

Ray. tune. error. TuneError: ('Trials did not complete', [A3C_cleanup_env_0])

Can you help me solve this problem if you can?
Thank you very much.

**Comment by liuxgff** [comment]
Hello, tensorflow-gpu==1.12.0 in the requirements.txt file
I would like to ask if tensorflow can choose cup version.

**Comment by eugenevinitsky** [comment]
Hi, two questions:
1. Could you post the entirety of the error? The actual error is probably higher up in the printout.
2. What is a cup version?

**Comment by liuxgff** [comment]
![img1](https://user-images.githubusercontent.com/52727591/62029134-7abff000-b214-11e9-8c59-747836d4bd99.png)
![img2](https://user-images.githubusercontent.com/52727591/62029146-80b5d100-b214-11e9-9787-d9b5c5d5f120.png)
![img3](https://user-images.githubusercontent.com/52727591/62029157-86131b80-b214-11e9-9fb9-bb73eef1739c.png)

Hello,thank you very much for your reply. 

My question is this: I run "train_baseline.py" to get the result in the pictures, but I don't know how to use it.

Besides, I'm sorry, this is my spelling mistake. That's "cpu version" not "cup version".

**Comment by liuxgff** [comment]
Hello, I'd like to ask how I can use ~/ray_results/folder.
