### ISSUE TITLE
Can't run python -m pytest

### ISSUE THREAD

**Issue by sandguine** [eugenevinitsky/sequential_social_dilemma_games#160]
I followed the set up instruction in README.txt. I'm using macOS 10.14.6, anaconda 4.7.12, Python 3.6.7 inside "causal" environment.

However, when I cd to tests and run:

`python - m pytest`

Here is what I got:
`============================= test session starts ==============================
platform darwin -- Python 3.6.7, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /Users/sandy/sequential_social_dilemma_games
collected 0 items / 2 errors

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_envs.py ______________________
//anaconda3/envs/causal/lib/python3.6/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:971: in _find_and_load
    ???
<frozen importlib._bootstrap>:955: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:665: in _load_unlocked
    ???
//anaconda3/envs/causal/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:142: in exec_module
    exec(co, module.__dict__)
/Users/sandy/Dropbox/berkeley/projects/ssd/sequential_social_dilemma_games/tests/test_envs.py:9: in <module>
    ???
../social_dilemmas/envs/agent.py:6: in <module>
    import utility_funcs as util
../utility_funcs.py:3: in <module>
    import matplotlib.pyplot as plt
//anaconda3/envs/causal/lib/python3.6/site-packages/matplotlib/pyplot.py:115: in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
//anaconda3/envs/causal/lib/python3.6/site-packages/matplotlib/backends/__init__.py:62: in pylab_setup
    [backend_name], 0)
//anaconda3/envs/causal/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py:17: in <module>
    from matplotlib.backends import _macosx
E   RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
____________________ ERROR collecting tests/test_rollout.py ____________________
test_rollout.py:4: in <module>
    from rollout import Controller
../rollout.py:4: in <module>
    import utility_funcs
../utility_funcs.py:3: in <module>
    import matplotlib.pyplot as plt
//anaconda3/envs/causal/lib/python3.6/site-packages/matplotlib/pyplot.py:115: in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
//anaconda3/envs/causal/lib/python3.6/site-packages/matplotlib/backends/__init__.py:62: in pylab_setup
    [backend_name], 0)
//anaconda3/envs/causal/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py:17: in <module>
    from matplotlib.backends import _macosx
E   RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
=============================== 2 error in 1.93s ===============================`

Any suggestions?

**Comment by eugenevinitsky** [comment]
Ah yeah, this is a matplotlib error. 

Anywhere matplotlib is imported, replace it with 
```


import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
```

**Comment by sandguine** [comment]
That seems to solve the matplotlib problem! Thank you! 

But then these errors occur:
```
============================= test session starts ==============================
platform darwin -- Python 3.6.7, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /Users/sandy/Dropbox/berkeley/projects/ssd/games/sequential_social_dilemma_games
collected 0 items / 2 errors

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_envs.py ______________________
ImportError while importing test module '/Users/sandy/Dropbox/berkeley/projects/ssd/games/sequential_social_dilemma_games/tests/test_envs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py:41: in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:28: in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:24: in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
//anaconda3/envs/causal/lib/python3.6/imp.py:243: in load_module
    return load_dynamic(name, filename, file)
//anaconda3/envs/causal/lib/python3.6/imp.py:343: in load_dynamic
    return _load(spec)
E   ImportError: dlopen(//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
E     Referenced from: //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
E     Reason: image not found

During handling of the above exception, another exception occurred:
/Users/sandy/Dropbox/berkeley/projects/ssd/sequential_social_dilemma_games/tests/test_envs.py:15: in <module>
    ???
../social_dilemmas/envs/cleanup.py:5: in <module>
    from social_dilemmas.envs.map_env import MapEnv, ACTIONS
../social_dilemmas/envs/map_env.py:15: in <module>
    from ray.rllib.env import MultiAgentEnv
/Users/sandy/.local/lib/python3.6/site-packages/ray/rllib/__init__.py:11: in <module>
    from ray.rllib.evaluation.policy_graph import PolicyGraph
/Users/sandy/.local/lib/python3.6/site-packages/ray/rllib/evaluation/__init__.py:2: in <module>
    from ray.rllib.evaluation.policy_evaluator import PolicyEvaluator
/Users/sandy/.local/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py:8: in <module>
    import tensorflow as tf
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/__init__.py:24: in <module>
    from tensorflow.python import *
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/__init__.py:51: in <module>
    from tensorflow.python import pywrap_tensorflow
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py:52: in <module>
    raise ImportError(msg)
E   ImportError: Traceback (most recent call last):
E     File "//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
E       from tensorflow.python.pywrap_tensorflow_internal import *
E     File "//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
E       _pywrap_tensorflow_internal = swig_import_helper()
E     File "//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
E       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
E     File "//anaconda3/envs/causal/lib/python3.6/imp.py", line 243, in load_module
E       return load_dynamic(name, filename, file)
E     File "//anaconda3/envs/causal/lib/python3.6/imp.py", line 343, in load_dynamic
E       return _load(spec)
E   ImportError: dlopen(//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
E     Referenced from: //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
E     Reason: image not found
E   
E   
E   Failed to load the native TensorFlow runtime.
E   
E   See https://www.tensorflow.org/install/install_sources#common_installation_problems
E   
E   for some common reasons and solutions.  Include the entire stack trace
E   above this error message when asking for help.
------------------------------- Captured stderr --------------------------------
Couldn't import TensorFlow - disabling TensorBoard logging.
____________________ ERROR collecting tests/test_rollout.py ____________________
ImportError while importing test module '/Users/sandy/Dropbox/berkeley/projects/ssd/games/sequential_social_dilemma_games/tests/test_rollout.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py:41: in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:28: in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:24: in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
//anaconda3/envs/causal/lib/python3.6/imp.py:243: in load_module
    return load_dynamic(name, filename, file)
//anaconda3/envs/causal/lib/python3.6/imp.py:343: in load_dynamic
    return _load(spec)
E   ImportError: dlopen(//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
E     Referenced from: //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
E     Reason: image not found

During handling of the above exception, another exception occurred:
test_rollout.py:4: in <module>
    from rollout import Controller
../rollout.py:9: in <module>
    import tensorflow as tf
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/__init__.py:24: in <module>
    from tensorflow.python import *
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/__init__.py:51: in <module>
    from tensorflow.python import pywrap_tensorflow
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py:52: in <module>
    raise ImportError(msg)
E   ImportError: Traceback (most recent call last):
E     File "//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
E       from tensorflow.python.pywrap_tensorflow_internal import *
E     File "//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
E       _pywrap_tensorflow_internal = swig_import_helper()
E     File "//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
E       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
E     File "//anaconda3/envs/causal/lib/python3.6/imp.py", line 243, in load_module
E       return load_dynamic(name, filename, file)
E     File "//anaconda3/envs/causal/lib/python3.6/imp.py", line 343, in load_dynamic
E       return _load(spec)
E   ImportError: dlopen(//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
E     Referenced from: //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
E     Reason: image not found
E   
E   
E   Failed to load the native TensorFlow runtime.
E   
E   See https://www.tensorflow.org/install/install_sources#common_installation_problems
E   
E   for some common reasons and solutions.  Include the entire stack trace
E   above this error message when asking for help.
=============================== warnings summary ===============================
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warnings, 2 error in 1.03s =========================

```

**Comment by eugenevinitsky** [comment]
Oh boy, can you just try running `pip install tensorflow==1.14.0` and give this another go? I'm guessing your tensorflow version is messed up for some reason.

**Comment by sandguine** [comment]
I did the above command but these errors occur:
```
============================= test session starts ==============================
platform darwin -- Python 3.6.7, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /Users/sandy/Dropbox/berkeley/projects/ssd/games/sequential_social_dilemma_games
collected 1 item / 1 errors

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_envs.py ______________________
ImportError while importing test module '/Users/sandy/Dropbox/berkeley/projects/ssd/games/sequential_social_dilemma_games/tests/test_envs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/sandy/Dropbox/berkeley/projects/ssd/sequential_social_dilemma_games/tests/test_envs.py:15: in <module>
    ???
../social_dilemmas/envs/cleanup.py:5: in <module>
    from social_dilemmas.envs.map_env import MapEnv, ACTIONS
../social_dilemmas/envs/map_env.py:15: in <module>
    from ray.rllib.env import MultiAgentEnv
/Users/sandy/.local/lib/python3.6/site-packages/ray/rllib/__init__.py:11: in <module>
    from ray.rllib.evaluation.policy_graph import PolicyGraph
/Users/sandy/.local/lib/python3.6/site-packages/ray/rllib/evaluation/__init__.py:2: in <module>
    from ray.rllib.evaluation.policy_evaluator import PolicyEvaluator
/Users/sandy/.local/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py:20: in <module>
    from ray.rllib.evaluation.sampler import AsyncSampler, SyncSampler
/Users/sandy/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py:15: in <module>
    from ray.rllib.evaluation.tf_policy_graph import TFPolicyGraph
/Users/sandy/.local/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py:12: in <module>
    import ray.experimental.tf_utils
/Users/sandy/.local/lib/python3.6/site-packages/ray/experimental/tf_utils.py:8: in <module>
    from ray.rllib.utils import try_import_tf
E   ImportError: cannot import name 'try_import_tf'
------------------------------- Captured stderr --------------------------------
WARNING:tensorflow:From /Users/sandy/.local/lib/python3.6/site-packages/ray/tune/logger.py:22: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

=============================== warnings summary ===============================
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint8 = np.dtype([("qint8", np.int8, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint8 = np.dtype([("quint8", np.uint8, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint16 = np.dtype([("qint16", np.int16, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint16 = np.dtype([("quint16", np.uint16, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint32 = np.dtype([("qint32", np.int32, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    np_resource = np.dtype([("resource", np.ubyte, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint8 = np.dtype([("qint8", np.int8, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint8 = np.dtype([("quint8", np.uint8, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint16 = np.dtype([("qint16", np.int16, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint16 = np.dtype([("quint16", np.uint16, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint32 = np.dtype([("qint32", np.int32, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    np_resource = np.dtype([("resource", np.ubyte, 1)])

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 13 warnings, 1 error in 3.31s =========================

```
I'm not sure what exactly is the problem.

**Comment by eugenevinitsky** [comment]
Well in this case it seems rllib versioning is the issue. Hmm, not sure why this is happening at the moment, but you could try upgrading rllib slightly to like, 0.7.2.

**Comment by sandguine** [comment]
I tried to upgrade rllib as suggested but the same errors occurred.

Also this url in README.txt: https://github.com/ray-project/ray/blob/master/python/ray/rllib/env/multi_agent_env.py is not working anymore.

**Comment by sandguine** [comment]
got the line:
`python -m pytest`
to run by following the installation from wheel:
https://ray.readthedocs.io/en/latest/installation.html

then merge the folder with:
https://github.com/natashamjaques/ray.git

and got this as a result:
```
=================================== test session starts ===================================
platform darwin -- Python 3.6.7, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /Users/sandy/Dropbox/berkeley/projects/ssd/games/sequential_social_dilemma_games
collected 20 items

test_envs.py ...................                                                    [ 95%]
test_rollout.py .                                                                   [100%]

==================================== warnings summary =====================================
//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint8 = np.dtype([("qint8", np.int8, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint8 = np.dtype([("quint8", np.uint8, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint16 = np.dtype([("qint16", np.int16, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint16 = np.dtype([("quint16", np.uint16, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint32 = np.dtype([("qint32", np.int32, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    np_resource = np.dtype([("resource", np.ubyte, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint8 = np.dtype([("qint8", np.int8, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint8 = np.dtype([("quint8", np.uint8, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint16 = np.dtype([("qint16", np.int16, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_quint16 = np.dtype([("quint16", np.uint16, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    _np_qint32 = np.dtype([("qint32", np.int32, 1)])

//anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550
  //anaconda3/envs/causal/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
    np_resource = np.dtype([("resource", np.ubyte, 1)])

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================= 20 passed, 13 warnings in 4.99s =============================
```
thanks again!
